# Generated by Django 3.2.9 on 2021-12-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211211_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blogger',
            field=models.BooleanField(default=False),
        ),
    ]
