# Generated by Django 3.2.9 on 2021-12-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_is_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='profile_image',
            field=models.ImageField(default='blog/images/default.png', null=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(help_text='Blog author biography', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
    ]
