# Generated by Django 3.2.9 on 2021-12-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211218_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='dislikes',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='profile_image',
            field=models.ImageField(default='blog/images/default.png', null=True, upload_to='blog/images'),
        ),
    ]
