# Generated by Django 3.2.9 on 2022-01-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211225_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='blog/images/blog-default-image.png', null=True, upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='liked_disliked_users',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(help_text='Type in blog post content'),
        ),
    ]
