# Generated by Django 3.2.9 on 2022-01-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogpost_liked_disliked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='liked_disliked_users',
        ),
    ]
