# Generated by Django 3.2.9 on 2022-01-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_blogpost_liked_disliked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='liked_disliked_users',
            field=models.JSONField(null=True),
        ),
    ]
