# Generated by Django 3.2.9 on 2022-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogpost_liked_disliked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='liked_disliked_users',
            field=models.JSONField(default=dict),
        ),
    ]
