# Generated by Django 3.2.9 on 2022-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20220205_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('MU', 'Music'), ('FA', 'Fashion'), ('CA', 'Car'), ('TR', 'Travel'), ('TE', 'Technology'), ('MV', 'Movies'), ('HI', 'History'), ('LS', 'Lifestyle'), ('OV', 'Overall')], default='OV', help_text='Blogpost category', max_length=2),
        ),
    ]
