# Generated by Django 3.2.9 on 2022-05-07 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20220507_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
