# Generated by Django 3.2.9 on 2022-05-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_blogpost_viewed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='anonymous_users',
            field=models.JSONField(default=list),
        ),
    ]
