# Generated by Django 3.2.9 on 2022-05-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_blogpost_anonymous_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, null=True)),
                ('blogposts', models.ManyToManyField(blank=True, to='blog.BlogPost')),
            ],
        ),
    ]
