# Generated by Django 3.2.9 on 2022-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_tag_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
