# Generated by Django 3.2.9 on 2022-06-22 14:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_tag_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.CharField(default=blog.models.get_default_uuid, max_length=20, unique=True),
        ),
    ]
