# Generated by Django 3.2.9 on 2022-06-24 18:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_tag_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=tinymce.models.HTMLField(help_text='Type in blog post content'),
        ),
    ]
